### ISSUE TITLE
Error when generating calibration values

### ISSUE THREAD

**Issue by skartsiotis** [mapircamera/QGIS#10]
Hello,

I have the last Mapir_plugin package installed.
I have this error when generating calibration values using tiff images for Survey2 NIR camera (on the other hand, it works with the jpg photo):

Traceback (most recent call last):
			  File "C:/Users/Simone/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 395, in on_CalibrationGenButton_released
			    self.qrcoeffs = self.findQR(self.CalibrationQRFile.text())
			  File "C:/Users/Simone/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 854, in findQR
			    denoised = cv2.fastNlMeansDenoising(cl1, None, 14, 7, 21)
			error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\photo\src\denoising.cpp:142: error: (-5) Unsupported depth! Only CV_8U is supported for NORM_L2 in function cv::fastNlMeansDenoising

**Comment by mapircamera** [comment]
Hello, I noticed a small logic error and have fixed it in the latest package.

**Comment by skartsiotis** [comment]
With the new package, I still have the same error and I see two calibration tabs (see figure below).

Traceback (most recent call last):
			  File "C:/Users/Simone/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 556, in on_CalibrationGenButton_2_released
			    self.qrcoeffs2 = self.findQR(self.CalibrationQRFile_2.text())
			  File "C:/Users/Simone/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 1041, in findQR
			    denoised = cv2.fastNlMeansDenoising(cl1, None, 14, 7, 21)
			error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\photo\src\denoising.cpp:142: error: (-5) Unsupported depth! Only CV_8U is supported for NORM_L2 in function cv::fastNlMeansDenoising

![image](https://cloud.githubusercontent.com/assets/28369552/25862068/05e4122c-34e7-11e7-93a7-45da9e7c156b.png)

**Comment by mapircamera** [comment]
Hello, Sorry, I had uploaded the wrong UI file with version 1.1.2. I put up another version that should fix the issue. Sorry for any inconvenience.

Regards
