### ISSUE TITLE
Plugin is broken

### ISSUE THREAD

**Issue by lusignorelli** [mapircamera/QGIS#14]
I cannot load plugin MAPR_Processing on my windows 8 computer. It is giving the following error: 

```
Couldn't load plugin MAPIR_Processing due to an error when calling its classFactory() method 

ImportError: DLL load failed: %1 is not a valid Win32 application. 
Traceback (most recent call last):
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\MAPIR_Processing\__init__.py", line 34, in classFactory
    from .MAPIR_Processing import MAPIR_Processing
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\MAPIR_Processing\MAPIR_Processing.py", line 29, in 
    from MAPIR_Processing_dockwidget import MAPIR_ProcessingDockWidget
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 81, in 
    import cv2
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: %1 is not a valid Win32 application.


Python version: 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] 
QGIS version: 2.18.10 Las Palmas, 59e0f78 

Python Path:
C:\PROGRA~2\QGIS2~1.18\apps\qgis\python\plugins\MAPIR_Processing
C:\PROGRA~2\QGIS2~1.18\apps\qgis\python\plugins\MAPIR_Processing
C:\PROGRA~2\QGIS2~1.18\apps\qgis\python\plugins\MAPIR_Processing
C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:\Users\Mary\.qgis2\python\plugins\MAPIR_Processing
C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python
C:/Users/Mary/.qgis2/python
C:/Users/Mary/.qgis2/python/plugins
C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~2\QGIS2~1.18\bin\python27.zip
C:\PROGRA~2\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~2\QGIS2~1.18\bin
C:\PROGRA~2\QGIS2~1.18\apps\Python27
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win32.egg
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/Mary/.qgis2//python
```

**Comment by mapircamera** [comment]
Hello,

This is often cause because the files are not found in the right location. Ensure that the MAPIR_Processing folder under python/plugins has files in it and not another MAPIR_Processing folder, then restart your QGIS. If that doesn't work restarting your system sometimes will get it to work. Please let me know if that doesn't solve the issue.

**Comment by lusignorelli** [comment]
This is the path I am using:  ```C:\Users\Mary\.qgis2\python\plugins\MAPIR_Processing>```

And these are the files listed in the folder: 
```
Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         7/13/2017   2:12 PM            .idea
d----         7/13/2017   2:12 PM            help
d----         7/13/2017   2:12 PM            i18n
d----         7/13/2017   2:12 PM            scripts
d----         7/13/2017   2:12 PM            test
d----         7/13/2017   2:12 PM            __pycache__
-a---         5/11/2017   8:15 AM     165914 bitstring.py
-a---         5/11/2017   8:15 AM     149828 bitstring.pyc
-a---         5/11/2017   8:15 AM   46074368 cv2.pyd
-a---         5/11/2017   8:15 AM    3190052 cygwin1.dll
-a---         5/11/2017   8:15 AM     350440 dcraw
-a---         5/11/2017   8:15 AM     370080 dcraw.exe
-a---         5/11/2017   8:15 AM     270099 exiftool
-a---         5/11/2017   8:15 AM    7243730 exiftool.exe
-a---         5/11/2017   8:15 AM      12066 exiftool.py
-a---         5/11/2017   8:15 AM      12788 exiftool.pyc
-a---         5/11/2017   8:15 AM    5647360 FreeImage.dll
-a---         5/11/2017   8:15 AM     110080 FreeImagePlus.dll
-a---         5/11/2017   8:15 AM        857 icon.png
-a---         5/12/2017   1:59 PM         68 instring.txt
-a---         5/11/2017   8:15 AM       7307 Makefile
-a---         5/11/2017   8:15 AM    1544704 Mapir_Converter.exe
-a---         5/11/2017   8:15 AM       7951 MAPIR_Processing.py
-a---         5/11/2017   8:15 AM       7413 MAPIR_Processing.pyc
-a---         5/12/2017   1:43 PM      64722 MAPIR_Processing_dockwidget.py
-a---         5/12/2017   1:44 PM      35825 MAPIR_Processing_dockwidget.pyc
-a---         5/11/2017   8:15 AM      26467 MAPIR_Processing_dockwidget_base.ui
-a---         5/11/2017   8:15 AM       4417 MAPIR_Processing_dockwidget_modal.ui
-a---         5/11/2017   8:15 AM          0 mass_converter
-a---         5/11/2017   8:15 AM       1061 metadata.txt
-a---         5/11/2017   8:15 AM       2691 pb_tool.cfg
-a---         5/11/2017   8:15 AM       3217 plugin_upload.py
-a---         5/11/2017   8:15 AM       8798 pylintrc
-a---         5/11/2017   8:15 AM       1998 README.html
-a---         5/11/2017   8:15 AM        946 README.txt
-a---         5/11/2017   8:15 AM       5531 resouces_rc.py
-a---         5/11/2017   8:15 AM       5389 resources.py
-a---         5/11/2017   8:15 AM       1978 resources.pyc
-a---         5/11/2017   8:15 AM        112 resources.qrc
-ar--         8/26/2016   1:42 AM   14456872 vcredist_x86.exe
-a---         5/11/2017   8:15 AM       1565 __init__.py
-a---         5/11/2017   8:15 AM       1762 __init__.pyc
```

**Comment by mapircamera** [comment]
Okay, Are you using the latest version of QGIS? We haven't had a moment to test with the newest releases of QGIS.

**Comment by lusignorelli** [comment]
Yes, I am using the latest version of QGIS. Probably this is the cause of the error message. Let me try some old version of QGIS.
