### ISSUE TITLE
Plugin is broken: will not load in QGIS

### ISSUE THREAD

**Issue by bu-ra3y** [mapircamera/QGIS#7]
Tried with QGIS 2.18.2 and 2.18.6, both on Windows, both x64 versions.
Used MAPIR plugin 1.1.0

Stack trace when I start QGIS (as administrator):
```
Couldn't load plugin MAPIR_Processing due to an error when calling its classFactory() method 

ImportError: DLL load failed: The specified module could not be found. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/username/.qgis2/python/plugins\MAPIR_Processing\__init__.py", line 34, in classFactory
    from .MAPIR_Processing import MAPIR_Processing
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/username/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing.py", line 29, in 
    from MAPIR_Processing_dockwidget import MAPIR_ProcessingDockWidget
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/username/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 36, in 
    from scipy import stats
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\scipy\stats\__init__.py", line 334, in 
    from .stats import *
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\scipy\stats\stats.py", line 181, in 
    import scipy.special as special
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\scipy\special\__init__.py", line 546, in 
    from ._ufuncs import *
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified module could not be found.


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.6 Las Palmas, 5f369b0 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/username/.qgis2/python
C:/Users/username/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/username/.qgis2//python
```

**Comment by alcarazolabs** [comment]
https://github.com/mapircamera/QGIS/tree/master/Packages
Download the QGIS Package, I think it work

**Comment by mapircamera** [comment]
I've stated in previous issues, I'll have to add it in the instructions. Sometimes when the package is extracted it will contain a sub directory. You'll need to copy the sub directory to the specified location in the instructions.

**Comment by bu-ra3y** [comment]
Hi @mapircamera , I read the other issues and checked for that already.  
You can see in my stack trace that my plugin seems to be at the correct location:
```
"C:/Users/username/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing.py"
```

**Comment by mapircamera** [comment]
I'm looking into other solutions to this issue.

**Comment by mapircamera** [comment]
I can't seem to recreate this issue. The only thing I can think to suggest is installing the "Plugin builder" plugin. If that works, then I will add it as a prerequisite to using the MAPIR_Processing plugin.

**Comment by bu-ra3y** [comment]
@mapircamera , I installed the Plugin Builder, which didn't make the MAPIR plugin work.  Should I do anything with the Plugin Builder after installation?

**Comment by mapircamera** [comment]
No, I just wanted to make sure it had no bearing on the performance. As the original plugin was created with the plugin builder plugin. I am doing a fresh install of QGIS and a fresh download of the latest plugin to see if I have the same issue.

**Comment by bu-ra3y** [comment]
Just tried this again on a different computer. Steps to reproduce the issue, on my Windows 10 Home VM:

Following these instructions: https://github.com/mapircamera/QGIS

Install latest QGIS from: http://www.qgis.org/en/site/forusers/download.html
	I used version 2.18.6 x64

Download MAPIR plugin from: https://github.com/mapircamera/QGIS/tree/master/Packages
	version 1.1.0

Start QGIS Desktop as admin, close it

Move plugin (MAPIR_PROCESSING folder) into place (c:\Users\%USERNAME%\.qgis2\python\plugins)
	had to create the "plugins" directory, such that MAPIR_Processing.py is located at:
	C:\Users\%USRNAME%\.qgis2\python\plugins\MAPIR_Processing\MAPIR_Processing.py

Start QGIS Desktop as admin
	open plugins manager, see that MAPIR_PROCESSING plugin is red with an error:

```
Couldn't load plugin MAPIR_Processing due to an error when calling its classFactory() method 

ImportError: DLL load failed: The specified module could not be found. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/%USERNAME%/.qgis2/python/plugins\MAPIR_Processing\__init__.py", line 34, in classFactory
    from .MAPIR_Processing import MAPIR_Processing
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/%USERNAME%/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing.py", line 29, in 
    from MAPIR_Processing_dockwidget import MAPIR_ProcessingDockWidget
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/%USERNAME%/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 36, in 
    from scipy import stats
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\scipy\stats\__init__.py", line 334, in 
    from .stats import *
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\scipy\stats\stats.py", line 181, in 
    import scipy.special as special
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\scipy\special\__init__.py", line 546, in 
    from ._ufuncs import *
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified module could not be found.


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.6 Las Palmas, 5f369b0 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/%USERNAME%/.qgis2/python
C:/Users/%USERNAME%/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/%USERNAME%/.qgis2//python
```

**Comment by mapircamera** [comment]
Hello, I've dug through the stack trace, and it seems the problem is with the Scipy.stats module in the latest QGIS version. Try dialing back to an earlier version of QGIS while I check for a solution.

**Comment by bu-ra3y** [comment]
Able to work around this with 2.18.4, Windows installer found here: http://download.osgeo.org/qgis/windows/

**Comment by gisma** [comment]
Hi,
I am running in the same errors. Ubuntu 16.04 QGIS 2.18.6 and QGIS 2.14.x. Are you still focusing on the scipy.stats?

Konnte Erweiterung 'MAPIR_Processing' nicht laden 

ImportError: No module named cv2 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/creu/.qgis2/python/plugins/MAPIR_Processing/MAPIR_Processing.py", line 29, in 
    from MAPIR_Processing_dockwidget import MAPIR_ProcessingDockWidget
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/creu/.qgis2/python/plugins/MAPIR_Processing/MAPIR_Processing_dockwidget.py", line 81, in 
    import cv2
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named cv2


Python-Version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] 
QGIS-Version: 2.18.6 Las Palmas, 5f369b0

**Comment by mapircamera** [comment]
Hi Gisma,

I have not done any testing on Ubuntu. So far I am only supporting Windows with the QGIS plugin, and even then there seem to be some bugs with the latest version of QGIS and 32 bit Windows systems.
