### ISSUE TITLE
Generate Calibration Values: throws error

### ISSUE THREAD

**Issue by bu-ra3y** [mapircamera/QGIS#9]
QGIS 2.18.4
MAPIR_PROCESSING 1.1.0
  modified cv2tColor -> cvtColor
Camera: Survey2 NDVI

Calibration Tab, selected the shot of the calibration target, clicked "Generate Calibration Values" and the error below was thrown.  
After that when i click Calibrate, a new set of images is produced, but I'm not sure if they are correctly calibrated due to the error.

```
An error has occurred while executing Python code: 

error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\photo\src\denoising.cpp:142: error: (-5) Unsupported depth! Only CV_8U is supported for NORM_L2 in function cv::fastNlMeansDenoising 
Traceback (most recent call last):
  File "C:/Users/%USERNAME%/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 395, in on_CalibrationGenButton_released
    self.qrcoeffs = self.findQR(self.CalibrationQRFile.text())
  File "C:/Users/%USERNAME%/.qgis2/python/plugins\MAPIR_Processing\MAPIR_Processing_dockwidget.py", line 854, in findQR
    denoised = cv2.fastNlMeansDenoising(cl1, None, 14, 7, 21)
error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\photo\src\denoising.cpp:142: error: (-5) Unsupported depth! Only CV_8U is supported for NORM_L2 in function cv::fastNlMeansDenoising



Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.4 Las Palmas, 59c1d21 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:\Users\%USERNAME%\.qgis2\python\plugins\MAPIR_Processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/%USERNAME%/.qgis2/python
C:/Users/%USERNAME%/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/%USERNAME%/.qgis2//python
```

**Comment by mapircamera** [comment]
Hello,

There is a new version up that fixed the cv2tColor thing. Try that and see if it still gives the unsupported depth error.
